//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITD.Checkin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedTest_Signup
    {
        public int SpeedTest_ID { get; set; }
        public string NID { get; set; }
        public int Test_ID { get; set; }
        public string Email { get; set; }
        public string Cell_Phone_Number { get; set; }
        public System.DateTime Date_Time_Added { get; set; }
        public System.DateTime Date_Time_Requested { get; set; }
        public System.DateTime Date_Time_Expires { get; set; }
        public Nullable<System.DateTime> Date_Time_Accepted { get; set; }
        public Nullable<bool> Notify_Email { get; set; }
        public Nullable<bool> Notify_Cell { get; set; }
        public Nullable<int> TestSlotId { get; set; }
    }
}
