//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITD.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    
    public partial class CurrentTests
    {
        public int TestID { get; set; }
        public string CoursePrefix { get; set; }
        public string CourseNumber { get; set; }
        public string CourseTitle { get; set; }
        public string Professor { get; set; }
        public string CourseTest { get; set; }
        public System.DateTime TestOpens { get; set; }
        public System.DateTime TestCloses { get; set; }
        public int StudentsEnrolled { get; set; }
        public int TestsTaken { get; set; }
        public List<String> Sections { get; set; }
        public String strSections { get; set; }

        public void GetSections()
        {
            List<String> tempList = new List<String>();

            String query = @"SELECT CoursE_Section
                            FROM [cba_trc_01].[dbo].[tlTests_Courses] TC, tlCourses C
                            WHERE TC.Course_ID = C.Course_Id AND Test_ID = '" + TestID + "'";
            SqlConnection con = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["TL_Connection_String"].ConnectionString);
            SqlCommand cmd = new SqlCommand(query, con);

            con.Open();

            SqlDataReader rdr = cmd.ExecuteReader();

            while (rdr.Read())
            {
                tempList.Add(rdr[0].ToString());
            }
            con.Close();

            Sections = tempList;

            String strTemp = "";
            foreach (String section in Sections)
            {
                strTemp += (section + " ");
            }

            strSections = strTemp;
        }
    }
}
